### ISSUE TITLE
При нажатии на кнопку "Level Up" игра вылетает.

### ISSUE THREAD

**Issue by SkyForcesGit** [mrdivdiz/bpvita#5]
После прохождения нескольких уровней игра предлагает повысить уровень, что в итоге невозможно, так как **BP** систематически вылетает при нажатии на кнопку.
![pvUcH8pJ1PQ](https://user-images.githubusercontent.com/64554063/113518338-63f7a200-958e-11eb-98fd-9a8594ee34e1.jpg)

**Comment by mrdivdiz** [comment]
Попробую поправить.Но уровни лучше так-то убрать вообще, без донатного магазина они бесполезны.
Постараюсь убрать краш.
