### ISSUE TITLE
Physics bug in Courtroom

### ISSUE THREAD

**Issue by Shieldowskyy** [mrdivdiz/bpvita#9]
https://www.youtube.com/watch?v=lg4cWDeTNzo

**Comment by mrdivdiz** [comment]
Huh, i`ll try to fix that.

**Comment by NinjaWeedle** [comment]
This is actually how the food intentionally behaves in this version of the game iirc

**Comment by mrdivdiz** [comment]
Anyway. it is wrong and must be fixed.

**Comment by mrdivdiz** [comment]
So I checked another modded version on android.Basically, you can feed King Pig if you point desserts right on his mouth.So I`ll just close this issue.
